"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ehPjDVTl67X
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { differenceInMinutes, isBefore, isSameDay, startOfDay } from "date-fns";
import { useEffect, useMemo, useState } from "react";
import { type RouterOutputs } from "~/trpc/react";
import { calculateInstancesWithEventIndexes } from "~/utils/event-in-day-planner-utils";
import { SingleWoodstockEvent } from "./single-woodstock-event";
import { Button } from "./ui/button";
import { Drawer, DrawerContent } from "./ui/drawer";
import { ScrollArea, ScrollBar } from "./ui/scroll-area";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
type InstanceWithEvent = RouterOutputs["events"]["getEventsInstances"][number];
type InstanceWithEventWithHorizontalPosition = InstanceWithEvent & {
  horizontalPosition: number;
};
const scrollToInstance = ({ instanceId }: { instanceId: string }) => {
  // Select the element with the specific data attribute
  const element = document.querySelector(
    `[data-event-instance-id="${instanceId}"]`,
  );

  // Check if the element exists
  if (element) {
    // Scroll to the element
    element.scrollIntoView({ behavior: "smooth", block: "start" });
  } else {
    console.log("Element not found");
  }
};

export function V6({
  instancesDetails,
}: {
  instancesDetails: InstanceWithEvent[];
}) {
  const [selectedInstanceWithEvent, setSelectedInstanceWithEvent] = useState<
    InstanceWithEvent | undefined
  >();
  const [selectedDate, setSelectedDate] = useState(new Date("2024-07-31"));
  const instancesInSelectedDate = useMemo(
    () =>
      instancesDetails.filter(({ instance }) => {
        const instanceDateStart = new Date(instance.dateStart);
        const instanceDateEnd = new Date(instance.dateEnd);

        const isDuringSameDay =
          isSameDay(instanceDateStart, selectedDate) ||
          isSameDay(instanceDateEnd, selectedDate);
        console.log({
          isDuringSameDay,
          instanceDateStart,
          instanceDateEnd,
          selectedDate,
        });

        return isDuringSameDay;
      }),
    [instancesDetails, selectedDate],
  );

  const instancesWithHorizontalPosition = useMemo(
    () =>
      calculateInstancesWithEventIndexes({
        instancesWithEvents: instancesInSelectedDate,
      }),
    [instancesInSelectedDate],
  );
  const handleDateChange = (date: Date) => {
    setSelectedDate(date);
  };
  const firstInstanceId = useMemo(
    () =>
      instancesWithHorizontalPosition.sort((first, second) => {
        return isBefore(first.instance.dateEnd, second.instance.dateEnd)
          ? -1
          : 1;
      })[0]?.instance.id,
    [instancesWithHorizontalPosition],
  );
  useEffect(() => {
    if (firstInstanceId) {
      scrollToInstance({ instanceId: firstInstanceId });
    }
  }, [firstInstanceId]);
  const tenMinuteIntervalsInDay = 24 * 6;

  return (
    <div className="flex h-full w-full flex-col justify-between gap-4 bg-background p-4 text-foreground sm:p-6">
      <ScrollArea className="h-[70dvh]">
        <div
          className="mx-auto grid max-w-6xl grid-cols-8 gap-4"
          style={{
            gridTemplateRows: `repeat(${tenMinuteIntervalsInDay}, minmax(0, 1fr))`,
          }}
        >
          <div
            className="col-span-1 grid gap-0"
            style={{
              gridTemplateRows: `repeat(${24}, minmax(0, 1fr))`,
              gridRowStart: 1,
              gridRowEnd: `span ${tenMinuteIntervalsInDay}`,
            }}
          >
            {/* Hour Labels */}
            {[...Array.from({ length: 24 })].map((_, hour) => {
              const hourCellDate = new Date(
                `2024-07-29T${hour.toString().padStart(2, "0")}:00:00`,
              ).toLocaleTimeString([], {
                hour: "2-digit",
                minute: "2-digit",
              });

              const hourMinuteDelimeter = ":";
              const [hours, minutes] = hourCellDate.split(hourMinuteDelimeter);
              return (
                <div
                  key={hour}
                  className="flex flex-col items-center justify-center rounded-none bg-card bg-gray-100 p-2 text-card-foreground shadow-sm ring-1 ring-gray-200 sm:flex-row"
                >
                  <span>{hours}</span>
                  <span>{":"}</span>
                  <span>{minutes}</span>
                </div>
              );
            })}
          </div>

          <div
            className="col-span-7 grid grid-cols-12 gap-2 overflow-scroll"
            style={{
              gridTemplateRows: `repeat(${tenMinuteIntervalsInDay}, minmax(0, 1fr))`,
              gridRowStart: 1,
              gridRowEnd: `span ${tenMinuteIntervalsInDay}`,
            }}
          >
            {instancesWithHorizontalPosition.map((eventDetails) => {
              const dateStart = new Date(eventDetails.instance.dateStart);
              const colStart = eventDetails.instance.index + 1;
              const dateEnd = new Date(eventDetails.instance.dateEnd);
              const tenMinutesSegmentsDiff =
                differenceInMinutes(dateEnd, dateStart) / 10;
              const tenMinutesFromStartOfDayUntilEventStarts =
                differenceInMinutes(dateStart, startOfDay(dateStart)) / 10;

              return (
                <div
                  key={eventDetails.instance.id}
                  data-event-instance-id={eventDetails.instance.id}
                  // className={`col-start-${colStart} col-span-2 md:col-span-1 row-start-${minutesFromStartOfDayUntilEventStarts + 1} row-span-${minDiff} row-span-1 rounded-lg bg-gray-100 p-4`}
                  className={`col-start-${colStart} col-span-2 md:col-span-1 row-span-${tenMinutesSegmentsDiff} row-span-1 rounded-lg bg-gray-100 p-4`}
                  style={{
                    gridTemplateRows: `repeat(${tenMinuteIntervalsInDay}, minmax(0, 1fr))`,
                    gridRowEnd: `span ${tenMinutesSegmentsDiff} `,
                    gridRowStart: `${tenMinutesFromStartOfDayUntilEventStarts + 1}`,
                  }}
                  onClick={() => {
                    setSelectedInstanceWithEvent(eventDetails);
                    console.log({
                      eventDetails,
                      minutesFromStartOfDayUntilEventStarts:
                        tenMinutesFromStartOfDayUntilEventStarts,
                      tenMinutesSegmentsDiff,
                      hourDiff: tenMinutesSegmentsDiff / 6,
                    });
                  }}
                >
                  <h3 className="mb-2 truncate text-sm font-bold">
                    {eventDetails.event?.event ?? ""}
                  </h3>
                </div>
              );
            })}
          </div>
        </div>
      </ScrollArea>
      <ScrollArea className="flex w-full flex-nowrap gap-2">
        <div className="flex w-full justify-around space-x-4 p-4">
          {[
            { dateAsString: "2024-07-31", label: "Wednesday" },
            { dateAsString: "2024-08-01", label: "Thursday" },
            { dateAsString: "2024-08-02", label: "Friday" },
            { dateAsString: "2024-07-27", label: "Saturday" },
          ].map(({ dateAsString, label }) => (
            <Button
              variant="outline"
              key={dateAsString} // Corrected the spelling of 'kay' to 'key'
              onClick={() => handleDateChange(new Date(dateAsString))}
            >
              {label}
            </Button>
          ))}
        </div>
        <ScrollBar orientation="horizontal" />
      </ScrollArea>
      <Drawer
        open={!!selectedInstanceWithEvent?.event}
        onOpenChange={(open) => {
          if (!open) {
            setSelectedInstanceWithEvent(undefined);
          }
        }}
      >
        <DrawerContent>
          {selectedInstanceWithEvent?.event ? (
            <SingleWoodstockEvent
              woodstockEvent={selectedInstanceWithEvent.event}
            />
          ) : null}
        </DrawerContent>
      </Drawer>
    </div>
  );
}
